import tkinter
from tkinter import ttk
frm=tkinter.Tk()
frm.geometry('600x400')
lbl1=tkinter.Label(frm,text='lbl1',font='20')
btn1=tkinter.Button(frm,text='ok',font='20')
lbl1.grid(row=0,column=0)
btn1.grid(row=0,column=1)
lbl2=tkinter.Label(frm,text='lbl2',font='20')
btn2=tkinter.Button(frm,text='ok',font='20')
lbl2.grid(row=1,column=0)
btn2.grid(row=1,column=1)
lbl3=tkinter.Label(frm,text='lbl3',font=20)
lbl4=tkinter.Label(frm,text='lbl4',font='20')
lbl5=tkinter.Label(frm,text='lbl5',font='20')
lbl6=tkinter.Label(frm,text='lbl6',font='20')
lbl7=tkinter.Label(frm,text='lbl7',font='20')
lbl4.grid(row=2,column=0)
lbl3.grid(row=2,column=1)
lbl5.grid(row=2,column=2)
lbl6.grid(row=2,column=3)
lbl7.grid(row=2,column=4)
frm.mainloop()