import tkinter
from tkinter import ttk
from tkinter import messagebox
from tkinter import *
frm=tkinter.Tk()
frm.geometry('400x400')
lbl1=tkinter.Label(frm,text='company program')
lbl2=tkinter.Label(frm,text='---------------')
lbl3=tkinter.Label(frm,text='---------------')
def employee():
    form1=tkinter.Toplevel()
    form1.geometry('400x400')
    vnum=StringVar()
    vname=StringVar()
    vcity=StringVar()
    vphone=StringVar()
    vemail=StringVar()
    lbl4 = tkinter.Label(form1, text='number :')
    txt1=tkinter.ttk.Entry(form1,textvariable=vnum)
    lbl5 = tkinter.Label(form1, text='name :')
    txt2 = tkinter.ttk.Entry(form1,textvariable=vname)
    lbl6 = tkinter.Label(form1, text='city :')
    txt3=tkinter.ttk.Entry(form1,textvariable=vcity)
    lbl7 = tkinter.Label(form1, text='phone :')
    txt4=tkinter.ttk.Entry(form1,textvariable=vphone)
    lbl8 = tkinter.Label(form1, text='email :')
    txt5=tkinter.ttk.Entry(form1,textvariable=vemail)
    form2=tkinter.Frame(form1)
    btn5=tkinter.ttk.Button(form2,text='add',command=tkinter.messagebox.showinfo('','add ok'))
    btn6=tkinter.ttk.Button(form2,text='edit',command=tkinter.messagebox.showinfo('','edit ok'))
    btn7=tkinter.ttk.Button(form2,text='delete',command=tkinter.messagebox.showinfo('','delete ok'))
    btn8=tkinter.ttk.Button(form2,text='find',command=tkinter.messagebox.showinfo('','find ok'))
    form3=tkinter.Frame(form1)
    btn9=tkinter.ttk.Button(form3,text='exit',command=lambda :form1.destroy())
    lbl4.grid(row=0,column=0)
    txt1.grid(row=0, column=1)
    lbl5.grid(row=1, column=0)
    txt2.grid(row=1, column=1)
    lbl6.grid(row=2, column=0)
    txt3.grid(row=2, column=1)
    lbl7.grid(row=3, column=0)
    txt4.grid(row=3, column=1)
    lbl8.grid(row=4, column=0)
    txt5.grid(row=4, column=1)
    form2.grid(row=5,column=0,columnspan=2)
    btn5.grid(row=5,column=0)
    btn6.grid(row=5,column=1)
    btn7.grid(row=5,column=2)
    btn8.grid(row=5,column=3)
    form3.grid(row=6,column=0,columnspan=4)
    btn9.grid(row=0,column=0)
    form1.grab_set()
btn1=tkinter.ttk.Button(frm,text='employee',command=employee)
def department():
    form4=tkinter.Toplevel()
    form4.geometry('400x400')
    lbl9=tkinter.Label(form4,text='department number')
    txt6=tkinter.Entry(form4)
    lbl10=tkinter.Label(form4,text='department name')
    txt7=tkinter.Entry(form4)
    lbl11=tkinter.Label(form4,text='location')
    txt8=tkinter.Entry(form4)
    form5=tkinter.Frame(form4)
    btn10=tkinter.ttk.Button(form5,text='add')
    btn11=tkinter.ttk.Button(form5,text='edit')
    btn12=tkinter.ttk.Button(form5,text='delete')
    btn13=tkinter.ttk.Button(form5,text='find')
    form6=tkinter.Frame(form4)
    btn14=tkinter.ttk.Button(form6,text='exit',command=lambda :form4.destroy())
    lbl9.grid(row=0,column=0)
    txt6.grid(row=0,column=1)
    lbl10.grid(row=1,column=0)
    txt7.grid(row=1,column=1)
    lbl11.grid(row=2,column=0)
    txt8.grid(row=2,column=1)
    form5.grid(row=3,column=0,columnspan=2)
    btn10.grid(row=0,column=0)
    btn11.grid(row=0,column=1)
    btn12.grid(row=0,column=2)
    btn13.grid(row=0,column=3)
    form6.grid(row=4,column=0,columnspan=4)
    btn14.grid(row=0,column=0)
    form4.grab_set()
btn2=tkinter.ttk.Button(frm,text='department',command=department)
def item():
    form7=tkinter.Toplevel()
    form7.geometry('400x400')
    lbl12=tkinter.Label(form7,text='item number')
    txt9=tkinter.Entry(form7)
    lbl13=tkinter.Label(form7,text='item name')
    txt10=tkinter.Entry(form7)
    lbl14=tkinter.Label(form7,text='price')
    txt11=tkinter.Entry(form7)
    form8=tkinter.Frame(form7)
    btn15=tkinter.ttk.Button(form8,text='add')
    btn16=tkinter.ttk.Button(form8,text='edit')
    btn17=tkinter.ttk.Button(form8,text='delete')
    btn18=tkinter.ttk.Button(form8,text='find')
    form9=tkinter.Frame(form7)
    btn19=tkinter.ttk.Button(form9,text='exit',command=lambda :form7.destroy())
    lbl12.grid(row=0,column=0)
    txt9.grid(row=0,column=1)
    lbl13.grid(row=1,column=0)
    txt10.grid(row=1,column=1)
    lbl14.grid(row=2,column=0)
    txt11.grid(row=2,column=1)
    form8.grid(row=3,column=0,columnspan=2)
    btn15.grid(row=0,column=0)
    btn16.grid(row=0,column=1)
    btn17.grid(row=0,column=2)
    btn18.grid(row=0,column=3)
    form9.grid(row=4,column=0,columnspan=4)
    btn19.grid(row=0,column=0)
    form7.grab_set()
btn3=tkinter.ttk.Button(frm,text='item',command=item)
btn4=tkinter.ttk.Button(frm,text='exit',command=lambda :frm.destroy())
lbl1.pack(pady=10)
lbl2.pack(pady=10)
btn1.pack(pady=10)
btn2.pack(pady=10)
btn3.pack(pady=10)
btn4.pack(pady=10)
lbl3.pack(pady=10)
frm.mainloop()